# Generated by Django 4.0.8 on 2022-10-17 13:17

from django.db import migrations, models
from django.utils.text import slugify


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory', '0001_initial'),
    ]

    def migrate_data_forward(apps, schema_editor):
        Supplier = apps.get_model("netbox_inventory", "Supplier")
        for instance in Supplier.objects.all():
            print(f"Generating slug for {instance}")
            if not instance.slug:
                instance.slug = slugify(instance.name)
                instance.save()

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(null=True, default=None, max_length=100, unique=False),
            preserve_default=False,
        ),
        migrations.RunPython(
            migrate_data_forward,
            migrations.RunPython.noop,
        ),
    ]
