# Generated by Django 4.0.8 on 2022-10-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory', '0002_supplier_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
