# Generated by Django 4.0.8 on 2022-10-17 16:52

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory', '0003_alter_supplier_slug'),
    ]

    def migrate_data_forward(apps, schema_editor):
        Supplier = apps.get_model("netbox_inventory", "Supplier")
        Asset = apps.get_model("netbox_inventory", "Asset")
        Purchase = apps.get_model("netbox_inventory", "Purchase")
        for asset in Asset.objects.all():
            if asset.order_number and asset.supplier:
                purchase, new_purchase = Purchase.objects.get_or_create(name=asset.order_number, supplier=asset.supplier)
            elif asset.order_number:
                supplier, _ = Supplier.objects.get_or_create(name='Unknown')
                purchase, new_purchase = Purchase.object.get_or_create(name=asset.order_number, supplier=supplier)
            elif asset.supplier:
                purchase, new_purchase = Purchase.objects.get_or_create(name='Unknown', supplier=asset.supplier)
            else:
                continue
            if new_purchase:
                purchase.date = asset.purchase_date
                purchase.save()
            asset.purchase = purchase
            asset.save()


    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='netbox_inventory.supplier')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['supplier', 'name'],
                'unique_together': {('supplier', 'name')},
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='netbox_inventory.purchase'),
        ),

        migrations.RunPython(
            migrate_data_forward,
            migrations.RunPython.noop,
        ),

        migrations.RemoveField(
            model_name='asset',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='supplier',
        ),
    ]
