# Generated by Django 4.0.8 on 2022-10-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory', '0004_add_purchase'),
    ]

    def migrate_data_forward(apps, schema_editor):
        Asset = apps.get_model("netbox_inventory", "Asset")
        # update empty asset tags to null
        Asset.objects.filter(asset_tag='').update(asset_tag=None)

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),

        migrations.RunPython(
            migrate_data_forward,
            migrations.RunPython.noop,
        ),
    ]
