# Generated by Django 4.2.9 on 2024-02-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory', '0005_delivery_asset_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(default='closed', max_length=30),
            preserve_default=False,
        ),
    ]
