# Generated by Django 5.1.7 on 2025-03-25 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory', '0011_bom'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='netbox_inventory.bom'),
        ),
    ]
