# Generated by Django 4.2.16 on 2024-12-19 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory', '0012_contract_add_contact_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='contract',
            field=models.ForeignKey(
                blank=True,
                help_text='Contract associated with this asset',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='assets',
                to='netbox_inventory.contract'
            ),
        ),
    ] 