# Generated by Django 5.1.7 on 2025-03-25 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory', '0012_asset_bom'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='BOMs', to='netbox_inventory.purchase'),
        ),
    ]
