# Generated by Django 5.2.5 on 2025-08-31 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_inventory', '0013_add_audittrail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype'),
        ),
    ]
