# Generated by Django 5.1.6 on 2025-03-14 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('netbox_inventory', '0013_add_audittrail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='inventoryitem_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='assets',
                to='netbox_inventory.inventoryitemtype',
            ),
        ),
    ]
