# Generated by Django 5.1.7 on 2025-03-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory', '0013_bom_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bom',
            name='purchase',
        ),
        migrations.AddField(
            model_name='purchase',
            name='boms',
            field=models.ManyToManyField(blank=True, null=True, related_name='purchases', to='netbox_inventory.bom'),
        ),
    ]
