# Generated by Django 5.1.7 on 2025-04-05 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory', '0013_add_auditflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditflowpageassignment',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_pages', to='netbox_inventory.auditflow'),
        ),
    ]
