# Generated by Django 5.1.7 on 2025-03-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory', '0014_remove_bom_purchase_purchase_boms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='delivery',
            unique_together={('name',)},
        ),
        migrations.AddField(
            model_name='delivery',
            name='purchases',
            field=models.ManyToManyField(related_name='orders', to='netbox_inventory.purchase'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='boms',
            field=models.ManyToManyField(blank=True, related_name='purchases', to='netbox_inventory.bom'),
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='purchase',
        ),
    ]
