# Generated by Django 5.2.7 on 2025-10-22 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory', '0014_alter_audittrail_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='dcim.location'),
        ),
    ]
