# Generated by Django 5.1.6 on 2025-03-13 07:55

from django.db import migrations, models


def move_inventoryitem_types_groups(apps, schema_editor):
    # we need o move relation from InventoryItemType side (FK) to
    # InventoryItemGroup side (M2M)
    # We need to get existing data using old DB schema, but set data to
    # new schema.
    InventoryItemTypeOld = apps.get_model('netbox_inventory', 'InventoryItemType')
    from netbox_inventory.models import InventoryItemGroup, InventoryItemType

    for inventoryitem_type_old in InventoryItemTypeOld.objects.all():
        inventoryitem_type = InventoryItemType.objects.get(pk=inventoryitem_type_old.pk)
        if inventoryitem_type_old.inventoryitem_group:
            inventoryitem_group = InventoryItemGroup.objects.get(
                pk=inventoryitem_type_old.inventoryitem_group.pk
            )
            inventoryitem_group.inventoryitem_types.add(inventoryitem_type)


class Migration(migrations.Migration):
    dependencies = [
        ('netbox_inventory', '0014_alter_asset_inventoryitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitemgroup',
            name='inventoryitem_types',
            field=models.ManyToManyField(
                blank=True,
                related_name='inventoryitem_groups',
                to='netbox_inventory.inventoryitemtype',
            ),
        ),
        migrations.RunPython(
            move_inventoryitem_types_groups, migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='inventoryitemtype',
            name='inventoryitem_group',
        ),
    ]
