# Generated by Django 5.1.7 on 2025-04-03 04:30

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('extras', '0122_charfield_null_choices'),
        ('netbox_inventory', '0016_courier'),
        ('tenancy', '0017_natural_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('shipping_number', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(max_length=30)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='netbox_inventory.courier')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='dcim.location')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_transfers', to='tenancy.contact')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transfers', to='tenancy.contact')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('sender', 'pickup_date'),
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='netbox_inventory.transfer'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.UniqueConstraint(fields=('shipping_number',), name='unique_shipping_number', violation_error_message='Transfer with this Shipping Number already exists.'),
        ),
    ]
