# Generated by Django 5.2.9 on 2026-01-16 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0225_gfk_indexes'),
        ('extras', '0134_owner'),
        ('netbox_inventory', '0016_owner'),
        ('tenancy', '0022_add_comments_to_organizationalmodel'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asset',
            name='unique_owner_asset_tag',
        ),
        migrations.RemoveConstraint(
            model_name='asset',
            name='unique_asset_tag',
        ),
        # drop index for owner field before renaming
        # there is a RenameIndex in django but it doesn't seem to work
        migrations.AlterField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='owner',
            new_name='owning_tenant',
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('owning_tenant', 'asset_tag'), name='unique_owning_tenant_asset_tag'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(models.F('asset_tag'), condition=models.Q(('owning_tenant__isnull', True)), name='unique_asset_tag', violation_error_message='Asset with this Asset Tag and no Owning Tenant already exists.'),
        ),
        # recreate index for renamed field
        migrations.AlterField(
            model_name='asset',
            name='owning_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
    ]
