# Generated by Django 5.2.9 on 2026-01-13 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory', '0017_rename_asset_owner_to_owning_tenant'),
        ('users', '0015_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner'),
        ),
        migrations.AddField(
            model_name='auditflow',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner'),
        ),
        migrations.AddField(
            model_name='auditflowpage',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner'),
        ),
        migrations.AddField(
            model_name='audittrailsource',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner'),
        ),
        migrations.AddField(
            model_name='inventoryitemtype',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner'),
        ),
    ]
