# Generated by Django 5.1.7 on 2025-04-23 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('netbox_inventory', '0017_transfer_asset_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.location'),
        ),
    ]
