# Generated by Django 5.2.10 on 2026-02-07 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_inventory', '0018_add_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditflow',
            name='object_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label', 'dcim'), ('model__in', ('site', 'location', 'rack'))), on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='auditflowpage',
            name='object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype'),
        ),
    ]
